### PR TITLE
Applied patch for #5

### LINKED ISSUE #5: Using an HTML template
Can HTML templates be used without specifying a custom theme? I have `publish.html.template.file` pointing to a `docs/custom.mustache`, but none of the changes appear reflected in the live server. Custom CSS files appear to be working by setting `publish.html.css`.

### PR DESCRIPTION
**Pull request by darsnack**
Fix #5

### CODE REVIEW

**Comment by MichaelHatherly** [comment]
Thanks, we'll need to add some kind of regression tests as well. If you're not too sure how best to add one to exercise this I can add one (since it's not been documented at all yet by me.)

**Comment by darsnack** [comment]
As separate test set for templates that are not complete themes?

**Comment by MichaelHatherly** [comment]
Yeah, basically a copy of the `theme_test` project with a custom user template and then in `runtests.jl` check that the template has been applied correctly (by checking for some unique string in the final output files.)

**Comment by MichaelHatherly** [comment]
See https://github.com/MichaelHatherly/Publish.jl/commit/4e1af1412a8cf2c7d523527a15a1a8a395d10ea6. Feel free to cherrypick that onto your branch.

**Comment by darsnack** [comment]
@MichaelHatherly sorry I lost track of this. The tests you added should now be in there.

**Comment by MichaelHatherly** [comment]
No worries, I had also forgotten about it. Thanks for following up on it.

**Review by MichaelHatherly — APPROVED** [review]

**Pull request merged**
